### ISSUE TITLE
How to train stage2？

### ISSUE THREAD

**Issue by wwwbq** [suilin0432/SoS-WSOD#4]
I find that the paper says stage2 trained a fully supervised detectors, but  this repo used "ubteacher trainer" and "TwoStagePseudoLabGeneralizedRCNN" in the second stage (in voc_baseline.yaml), which seems like the semi-supervised method, I am wondering whether the “BaselineTrainer‘ should be used here

**Comment by suilin0432** [comment]
Thanks for your comment~
I use the TwoStagePseudoLabGeneralizedRCNN because I want to ignore the annoying checkpoint converting process. So I split the dataset into n-1 pseudo-labeled images and 1 unlabeled image (n is the number of the dataset) as shown in config files. This setting can be regarded as the same as that using the BaselineTrainer. Before I built this repo, I tried to use official detectron2 to perform stage 2 and got a similar performance.

**Comment by wwwbq** [comment]
> Thanks for your comment~ I use the TwoStagePseudoLabGeneralizedRCNN because I want to ignore the annoying checkpoint converting process. So I split the dataset into n-1 pseudo-labeled images and 1 unlabeled image (n is the number of the dataset) as shown in config files. This setting can be regarded as the same as that using the BaselineTrainer. Before I built this repo, I tried to use official detectron2 to perform stage 2 and got a similar performance.

Thanks for your help !
